### ISSUE TITLE
passkeys page not working

### ISSUE THREAD

**Issue by tahvane1** [keycloakify/keycloakify#631]
When using passkeys functionality  page "resets" to default theme. There is not even kcContext.

**Comment by garronej** [comment]
Hello @tahvane1,  

Yes OK. I realize the page where added in Keycloak 25. I'm adding them right now.  

PS: For anyone reading this, when I'm behind for adding pages to the default set you can add them manually following this guide: https://docs.keycloakify.dev/styling-custom-extension-page

**Comment by garronej** [comment]
Hello @tahvane1,  
I've released a candidate. Can you try with Keycloakify 10.1.0-rc.0  and tell me if it works?  

If you could be kind enough for copy passting the kcContext you get for:  
login-passkeys-conditional-authenticate.ftl and login-idp-link-confirm-override.ftl it would be great, it willd enable me to provide better default mock for storybook.  

Thank you for your help

**Comment by tahvane1** [comment]
Received error message Uncaught TypeError: Failed to resolve module specifier "rfc4648". Relative references must start with either "/", "./", or "../".

kcContext

{
    "userVerification": "required",
    "social": {
        "displayInfo": true,
        "providers": [
            {
                "displayName": "Confidently Entra id",
                "providerId": "oidc",
                "loginUrl": "/realms/meo/broker/oidc/login?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9&session_code=N6Fx55SFSSrDJtI5DQMXwSHDT0tHE2sZCva0aRM5thQ",
                "iconClasses": "",
                "alias": "oidc"
            }
        ]
    },
    "auth": {
        "showResetCredentials": false,
        "authenticationSelections": [
            {
                "helpText": "auth-username-password-form-help-text",
                "displayName": "auth-username-password-form-display-name",
                "iconCssClass": "kcAuthenticatorDefaultClass",
                "authExecId": "ed879563-e2f7-4bd9-9ca2-92a04160e2ae",
                "authenticationExecution": {
                    "authenticatorFlow": false,
                    "conditional": false,
                    "required": true,
                    "enabled": true,
                    "disabled": false,
                    "id": "ed879563-e2f7-4bd9-9ca2-92a04160e2ae",
                    "parentFlow": "964c7020-afe2-4952-933d-1f887998a8f4",
                    "authenticator": "auth-username-password-form",
                    "alternative": false,
                    "requirement": {
                        "stableIndex": 0
                    },
                    "priority": 10
                }
            },
            {
                "helpText": "webauthn-passwordless-help-text",
                "displayName": "webauthn-passwordless-display-name",
                "iconCssClass": "kcAuthenticatorWebAuthnPasswordlessClass",
                "authExecId": "160b9597-9f58-4ff2-81e9-35fae444e75b",
                "authenticationExecution": {
                    "authenticatorFlow": false,
                    "conditional": false,
                    "required": false,
                    "enabled": true,
                    "disabled": false,
                    "id": "160b9597-9f58-4ff2-81e9-35fae444e75b",
                    "parentFlow": "bbf79e08-1ae0-4de3-9fd5-b498e6eedb6b",
                    "authenticator": "passkeys-authenticator",
                    "alternative": true,
                    "requirement": {
                        "stableIndex": 2
                    },
                    "priority": 32
                }
            }
        ],
        "showUsername": false,
        "showTryAnotherWayLink": true
    },
    "rpId": "auth.confidently.fi",
    "locale": {
        "current": "English",
        "supported": [
            {
                "languageTag": "en",
                "label": "English",
                "url": "/realms/meo/login-actions/authenticate?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9&execution=160b9597-9f58-4ff2-81e9-35fae444e75b&kc_locale=en"
            },
            {
                "languageTag": "fi",
                "label": "Finnish (Suomi)",
                "url": "/realms/meo/login-actions/authenticate?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9&execution=160b9597-9f58-4ff2-81e9-35fae444e75b&kc_locale=fi"
            },
            {
                "languageTag": "sv",
                "label": "Swedish (Svenska)",
                "url": "/realms/meo/login-actions/authenticate?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9&execution=160b9597-9f58-4ff2-81e9-35fae444e75b&kc_locale=sv"
            }
        ],
        "currentLanguageTag": "en"
    },
    "login": {},
    "url": {
        "oauthAction": "/realms/meo/login-actions/authenticate",
        "resourcesPath": "/resources/0pzc5/login/confidently-meo",
        "loginAction": "https://auth.confidently.fi/realms/meo/login-actions/authenticate?session_code=N6Fx55SFSSrDJtI5DQMXwSHDT0tHE2sZCva0aRM5thQ&execution=160b9597-9f58-4ff2-81e9-35fae444e75b&client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9",
        "loginUrl": "/realms/meo/login-actions/authenticate?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9",
        "resourcesCommonPath": "/resources/0pzc5/login/confidently-meo/resources-common",
        "firstBrokerLoginUrl": "/realms/meo/login-actions/first-broker-login?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9",
        "registrationUrl": "/realms/meo/login-actions/registration?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9",
        "logoutConfirmAction": "/realms/meo/protocol/openid-connect/logout/logout-confirm?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9",
        "registrationAction": "https://auth.confidently.fi/realms/meo/login-actions/authenticate?session_code=N6Fx55SFSSrDJtI5DQMXwSHDT0tHE2sZCva0aRM5thQ&execution=160b9597-9f58-4ff2-81e9-35fae444e75b&client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9",
        "loginResetCredentialsUrl": "/realms/meo/login-actions/reset-credentials?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9",
        "ssoLoginInOtherTabsUrl": "/realms/meo/login-actions/restart?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9&skip_logout=true",
        "resourcesUrl": "/resources/0pzc5?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9/login/confidently-meo",
        "loginRestartFlowUrl": "/realms/meo/login-actions/restart?client_id=SN4MEO&tab_id=PieMGwbPEaI&client_data=eyJydSI6Imh0dHBzOi8vbWVvLnNuNG1vYmlsZS5jb20vU040TUVPL29pZGNfY2FsbGJhY2tfaGFuZGxlciIsInJ0IjoiY29kZSJ9&skip_logout=false",
        "oauth2DeviceVerificationAction": "/realms/meo/login-actions/authenticate"
    },
    "authenticationSession": {
        "tabId": "PieMGwbPEaI",
        "authSessionId": "78e255c2-9d4e-49db-8220-117571c749ca"
    },
    "createTimeout": 0,
    "messagesPerField": {},
    "shouldDisplayAuthenticators": false,
    "challenge": "R5NDVgP0TCW-TQSyv5vHxg",
    "client": {
        "clientId": "SN4MEO",
        "description": "",
        "baseUrl": "",
        "name": "SN4MEO",
        "attributes": {
            "oidc.ciba.grant.enabled": "false",
            "client.secret.creation.time": "1724230027",
            "backchannel.logout.session.required": "true",
            "post.logout.redirect.uris": "http://meotest.confidently.fi/SN4MEO/index.faces##http://meo.confidently.fi/SN4MEO/index.faces##http://meo.sn4mobile.com/SN4MEO/index.faces",
            "oauth2.device.authorization.grant.enabled": "false",
            "display.on.consent.screen": "false",
            "backchannel.logout.revoke.offline.tokens": "false"
        }
    },
    "passwordPolicies": {
        "notEmail": false,
        "notUsername": false
    },
    "realm": {
        "displayName": "meo",
        "registrationAllowed": false,
        "displayNameHtml": "<div class=\"confidently-logo-text\"/>",
        "resetPasswordAllowed": true,
        "resetCredentialsActionTokenLifespanMinutes": 5,
        "password": true,
        "actionTokenGeneratedByUserLifespanMinutes": 5,
        "internationalizationEnabled": true,
        "idpVerifyAccountLinkActionTokenLifespanMinutes": 5,
        "verifyEmailActionTokenLifespanMinutes": 5,
        "loginWithEmailAllowed": true,
        "duplicateEmailsAllowed": false,
        "editUsernameAllowed": false,
        "name": "meo",
        "rememberMe": true,
        "registrationEmailAsUsername": false,
        "identityFederationEnabled": true
    },
    "scripts": [],
    "isUserIdentified": "false",
    "properties": {},
    "keycloakifyVersion": "10.1.0-rc.1",
    "themeVersion": "0.0.0",
    "themeType": "login",
    "themeName": "confidently-meo",
    "pageId": "login-passkeys-conditional-authenticate.ftl",
    "ftlTemplateFileName": "login-passkeys-conditional-authenticate.ftl",
    "x-keycloakify": {
        "resourcesPath": "/resources/0pzc5/login/confidently-meo",
        "messages": {
            "auth-username-password-form-help-text": "Sign in by entering your username and password.",
            "auth-username-password-form-display-name": "Username and password",
            "webauthn-passwordless-help-text": "Use your Passkey for passwordless sign in.",
            "webauthn-passwordless-display-name": "Passkey"
        }
    }
}

**Comment by garronej** [comment]
Ok thanks for the feedback I'll fix it

**Comment by garronej** [comment]
Should be fixed now in Keycloakify 10.1.0 let me know if there is any issue

**Comment by tahvane1** [comment]
i'm still having issues. 
VM214:13 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at <anonymous>:13:32

**Comment by garronej** [comment]
Can you give me more info to reproduce?
